selection:
	gcc main.c selection_sort.c -o selection.out
insertion:
	gcc main.c insertion_sort.c -o insertion.out
bubble:
	gcc main.c bubble_sort.c -o bubble.out
shaker:
	gcc main.c shaker_sort.c -o shaker.out
all: selection insertion bubble shaker