m1:
	gcc main.c merge.c -o m1.out
m2:
	gcc main.c merge2.c -o m2.out
m3:
	gcc main.c merge3.c -o m3.out
m4:
	gcc main.c merge4.c -o m4.out
m5:
	gcc main.c merge5.c -o m5.out
m6:
	gcc main.c merge6.c -o m6.out
m7:
	gcc main.c merge7.c -o m7.out
all: m1 m2 m3 m4 m5 m6 m7
